# Generated by Django 3.2 on 2021-04-30 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45, unique=True)),
                ('description', models.CharField(max_length=500)),
                ('price', models.FloatField()),
                ('stock', models.IntegerField()),
                ('category', models.IntegerField()),
                ('image', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'products',
            },
        ),
    ]
